default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: bang_bang_dev

test:
  <<: *default
  database: bang_bang_test

production:
  <<: *default
  database: bang_bang_production
